//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriGo.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FriGo.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountEndpointName {
            get {
                return ResourceManager.GetString("AccountEndpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FriGo.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Account/Token.
        /// </summary>
        internal static string AuthTokenRoute {
            get {
                return ResourceManager.GetString("AuthTokenRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formData.
        /// </summary>
        internal static string FormDataParameterTypeName {
            get {
                return ResourceManager.GetString("FormDataParameterTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grant_type.
        /// </summary>
        internal static string GrantTypeName {
            get {
                return ResourceManager.GetString("GrantTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferably grant_type=password.
        /// </summary>
        internal static string GrantTypeParameterDescription {
            get {
                return ResourceManager.GetString("GrantTypeParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient was not found in our database..
        /// </summary>
        internal static string IngredientNotFoundMessage {
            get {
                return ResourceManager.GetString("IngredientNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided request was invalid.
        /// </summary>
        internal static string InvalidRequestString {
            get {
                return ResourceManager.GetString("InvalidRequestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string PasswordParameterName {
            get {
                return ResourceManager.GetString("PasswordParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token granted.
        /// </summary>
        internal static string TokenGetString {
            get {
                return ResourceManager.GetString("TokenGetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        internal static string UrlEncodedContentType {
            get {
                return ResourceManager.GetString("UrlEncodedContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string UsernameParameterName {
            get {
                return ResourceManager.GetString("UsernameParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\bin\FriGo.Api.XML.
        /// </summary>
        internal static string XmlCommentsPath {
            get {
                return ResourceManager.GetString("XmlCommentsPath", resourceCulture);
            }
        }
    }
}
